// Regenerates src/main/db/schemaSql.ts from prisma/migrations/*/migration.sql
// Run this after creating a new migration with `npx prisma migrate dev --name <x>`.
const fs = require('fs')
const path = require('path')

const migrationsDir = path.join(__dirname, '..', 'prisma', 'migrations')
const folders = fs
  .readdirSync(migrationsDir)
  .filter((f) => fs.statSync(path.join(migrationsDir, f)).isDirectory())
  .sort()

const migrations = folders.map((folder) => {
  const sqlPath = path.join(migrationsDir, folder, 'migration.sql')
  const sql = fs.readFileSync(sqlPath, 'utf-8')
  return { name: folder, sql }
})

const outPath = path.join(__dirname, '..', 'src', 'main', 'db', 'schemaSql.ts')
const content = `// AUTO-GENERATED by scripts/embed-schema.cjs — do not edit by hand.
// Source: prisma/migrations/*/migration.sql
export interface EmbeddedMigration {
  name: string
  sql: string
}

export const MIGRATIONS: EmbeddedMigration[] = ${JSON.stringify(migrations, null, 2)}
`
fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, content, 'utf-8')
console.log('Wrote', outPath, `(${folders.length} migration(s) embedded)`)
